CREATE TABLE ADMIN(
    ID INT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROLE_ID INT
    
    
);
CREATE TABLE ROLE(
    ID INT NOT NULL,
    ROLE VARCHAR(255)  
);
CREATE TABLE INFO(
    ID INT NOT NULL,
    ABOUT VARCHAR(6000),
    ADRESS VARCHAR(255),
    PHONE INT,
    LINKEDIN VARCHAR(255),
    INSTAGRAM VARCHAR(255),
    TWITTER VARCHAR(255),
    EMAIL VARCHAR(255)
    
    
);
CREATE TABLE CAPTAIN(
    ID INT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    TEAM_ID INT
    
    
);



CREATE TABLE STUDENT(
    ID INT NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    TEAM_ID INT
    

);


CREATE TABLE TEAM(
    ID INT NOT NULL,
    DEPARTMENT VARCHAR(255),
    NAME VARCHAR(255),
    INFO VARCHAR(255)
    
);

CREATE TABLE BULLETIN(
    ID INT NOT NULL,
    HEAD VARCHAR(255),
    TEXTS TEXT
    
);


ALTER TABLE ADMIN ADD CONSTRAINT CONSTRAINT_1 PRIMARY KEY(ID);
ALTER TABLE CAPTAIN ADD CONSTRAINT CONSTRAINT_2 PRIMARY KEY(ID);
ALTER TABLE STUDENT ADD CONSTRAINT CONSTRAINT_3 PRIMARY KEY(ID);
ALTER TABLE TEAM ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(ID);
ALTER TABLE INFO ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY(ID);
ALTER TABLE ROLE ADD CONSTRAINT CONSTRAINT_8 PRIMARY KEY(ID);
ALTER TABLE BULLETIN ADD CONSTRAINT CONSTRAINT_10 PRIMARY KEY(ID);

ALTER TABLE CAPTAIN ADD CONSTRAINT CONSTRAINT_5 FOREIGN KEY(TEAM_ID) references TEAM(ID);
ALTER TABLE STUDENT ADD CONSTRAINT CONSTRAINT_6 FOREIGN KEY(TEAM_ID) references TEAM(ID);
ALTER TABLE ADMIN ADD CONSTRAINT CONSTRAINT_9 FOREIGN KEY(ROLE_ID) references ROLE(ID);









