INSERT INTO TEAM(ID,DEPARTMENT,NAME,INFO) VALUES (1,'SAGLIKTA YAPAY ZEKA','TAKIM1','SAGLIK UZERINDE YAPAY ZEKA CALISMALARI YAPAN TAKIMIMIZDIR')
INSERT INTO TEAM(ID,DEPARTMENT,NAME,INFO) VALUES (2,'ULASIMDA YAPAY ZEKA','TAKIM2','ULASIM UZERINDE YAPAY ZEKA CALISMALARI YAPAN TAKIMIMIZDIR')
INSERT INTO TEAM(ID,DEPARTMENT,NAME,INFO) VALUES (3,'EGITIMDE YAPAY ZEKA','TAKIM3','EGITIM UZERINDE YAPAY ZEKA CALISMALARI YAPAN TAKIMIMIZDIR')


INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (1,'AYSE','YILMAZ','BILGISAYAR MUHENDISI',1)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (2,'FATMA','GUCLU','MAKINE MUHENDISI',1)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (3,'ALI','SANSLI','BILGISAYAR MUHENDISI',1)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (4,'MEHMET','CICEK','ELEKTRIK MUHENDISI',1)

INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (5,'NUR','SOLMAZ','BILGISAYAR MUHENDISI',2)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (6,'GUL','DEMIR','MAKINE MUHENDISI',2)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (7,'ZEHRA','TOPRAK','MAKINE MUHENDISI',2)

INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (8,'AHMET','YILDIRIM','BILGISAYAR MUHENDISI',3)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (9,'YASIN','YIKILMAZ','ELEKTRIK MUHENDISI',3)
INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,DEPARTMENT,ID) VALUES (10,'MURAT','SIMSEK','BILGISAYAR MUHENDISI',3)

INSERT INTO CAPTAIN(ID,FIRST_NAME,LAST_NAME,EMAIL,DEPARTMENT,ID) VALUES (1,'BUSRA','ASLAN','ELEKTRIK MUHENDISI',1)
INSERT INTO CAPTAIN(ID,FIRST_NAME,LAST_NAME,EMAIL,DEPARTMENT,ID) VALUES (2,'CAN','CAKIR','MAKINE MUHENDISI',2)
INSERT INTO CAPTAIN(ID,FIRST_NAME,LAST_NAME,EMAIL,DEPARTMENT,ID) VALUES (3,'DILARA','GUZEL','BILGISAYAR MUHENDISI',3)


INSERT INTO INFO(ID,ABOUT,ADRESS,PHONE,LINKEDIN,INSTAGRAM,TWITTER) VALUES (1,'DFSDFS','Konya Teknik Universitesi','ktun@ailab.tr','HTTPS://WWW.LINKEDIN.COM/KTUN-AI-LAB','HTTPS://WWW.INSTAGRAM.COM/KTUN-AI-LAB','HTTPS://WWW.TWITTER.COM/KTUN-AI-LAB')

